config/routes.rb
Antiplug::Application.routes.draw do
  resources :check_texts

  resources :local_texts

  resources :authors

  resources :files
  match '/files/new', :to => 'files#new', :as => :new_files

  root :to => 'authors#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :detail_info, :name

  validates :name, presence: true, length: { minimum: 5 }, format: {
		with: %r{[[:word:]]+ [[:word:]]+.*}i,
		message: 'Введите имя и фамилию'
	}

	has_many :local_texts, dependent: :destroy
	
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
<fieldset>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <div class="input-prepend">
      <span class="add-on">ФИО</span>
      <%= f.text_field :name, class: 'prependedInput' %>
    </div>
  </div>
  <div class="field">
    <div class="input-prepend">
      <span class="add-on">Информация</span>
      <%= f.text_field :detail_info, class: 'input-xxlarge prependedInput' %>
    </div>
  </div>
  <div class="form-actions">
    <%= submit_tag 'Отправить', class: "btn btn-primary" %>
    <%= link_to 'Отмена', authors_path, class: "btn" %>
  </div>
</fieldset>
<% end %>

app/views/authors/edit.html.erb
<legend>
	Редактирование данных об авторе
</legend>
<%= render 'form' %>

app/views/authors/index.html.erb
<div class="page-header">
  <h1>Список авторов</h1>
  <small>
  <ul class="nav nav-pills">
    <li><%= link_to 'Добавить автора', new_author_path %></li>
  </ul>
</small>
</div>

<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Имя</th>
      <th>Информация</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <td width="20%"><%= author.name %></td>
      <td><%= author.detail_info %></td>
      <td width="1%">
        <div class="btn-group">
          <%= link_to raw('<i class="icon-align-justify icon-white"></i>'), author, class: 'btn btn-info btn-mini' %>
          <%= link_to raw('<i class="icon-edit icon-white"></i>'), edit_author_path(author),
            class: 'btn btn-warning btn-mini' %>
          <%= link_to raw('<i class="icon-trash icon-white"></i>'), author,
            method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-mini' %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<legend>
	Добавить автора
</legend>
<%= render 'form' %>

app/views/authors/show.html.erb
<div class="well">
	<p id="notice"><%= notice %></p>
	<p>
	  <b>Name:</b>
	  <i><%= @author.name %></i>
	</p>

	<p>
	  <b>Detail info:</b>
	  <p>
	  	<i><%= @author.detail_info %></i>
	  </p>
	</p>
</div>

<div class="form-actions">
	<%= link_to 'Edit', edit_author_path(@author), class: 'btn btn-warning' %>
	<%= link_to 'Back', authors_path, class: 'btn' %>
</div>