config/routes.rb
Antiplug::Application.routes.draw do
  resources :check_texts

  resources :local_texts

  resources :authors

  resources :files
  match '/files/new', :to => 'files#new', :as => :new_files

  root :to => 'authors#index'

end

app/models/local_text.rb
class LocalText < ActiveRecord::Base
  attr_accessible :author_id, :text, :title
  belongs_to :author
  has_many :words_pos, dependent: :destroy
  
  validates :author_id, :text, :title, presence: true
  validates :title, length: { minimum: 6 }, uniqueness: true
  validates :text, length: { minimum: 40 }
end

app/controllers/local_texts_controller.rb
class LocalTextsController < ApplicationController
  # GET /local_texts
  # GET /local_texts.json
  def index
    @local_texts = LocalText.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @local_texts }
    end
  end

  # GET /local_texts/1
  # GET /local_texts/1.json
  def show
    @local_text = LocalText.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @local_text }
    end
  end

  # GET /local_texts/new
  # GET /local_texts/new.json
  def new
    @local_text = LocalText.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @local_text }
    end
  end

  # GET /local_texts/1/edit
  def edit
    @local_text = LocalText.find(params[:id])
  end

  # POST /local_texts
  # POST /local_texts.json
  def create
    @local_text = LocalText.new(params[:local_text])
    files = params[:local_text][:file]
    if !files.nil?
      @file = files.read
    end

    respond_to do |format|
      if @local_text.save
        words_count = 0
        bench = Benchmark.measure { words_count = add_text(@local_text.text, @local_text.id) }.real

        format.html { redirect_to @local_text, notice: "Text was successfully added. 
          Time of indexing: #{sprintf("%2.3f", bench)} (#{sprintf("%2.5f/word", bench/words_count)})" }
        format.json { render json: @local_text, status: :created, location: @local_text }
      else
        format.html { render action: "new" }
        format.json { render json: @local_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /local_texts/1
  # PUT /local_texts/1.json
  def update
    @local_text = LocalText.find(params[:id])

    respond_to do |format|
      if @local_text.update_attributes(params[:local_text])
        Word.destroy_all(local_text_id: @local_text.id)
        add_text(@local_text.text, @local_text.id)
        format.html { redirect_to @local_text, notice: 'Local text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @local_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_texts/1
  # DELETE /local_texts/1.json
  def destroy
    @local_text = LocalText.find(params[:id])
    @local_text.destroy

    respond_to do |format|
      format.html { redirect_to local_texts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/local_texts_helper.rb
module LocalTextsHelper
end

app/views/local_texts/_form.html.erb
<%= form_for(@local_text) do |f| %>
  <% if @local_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local_text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @local_text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-prepend">
    <div class="field">
      <span class="add-on">Название</span>
      <%= f.text_field :title, class: 'input-xxlarge prependedInput' %>
    </div>
  </div>
  <div class="input-prepend pull-right">
    <div class="field">
      <span class="add-on">Автор</span>
      <%= f.select :author_id, Author.all.map { |e| e = [e.name, e.id] }, class: 'prependedInput' %>
    </div>
  </div>
  <div class="field">
    <%= f.label 'Текст' %>
    <%= f.text_area :text, class: 'input-block-level' %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Добавить', class: "btn btn-primary" %>
    <%= link_to 'Отмена', local_texts_path, class: "btn" %>
  </div>
<% end %>

app/views/local_texts/edit.html.erb
<legend>
	Редактирование текста
</legend>
<%= render 'form' %>

app/views/local_texts/index.html.erb
<div class="page-header">
<h1>Список текстов</h1>
<small>
  <ul class="nav nav-pills">
    <li><%= link_to 'Добавить текст', new_local_text_path %></li>
    <li><%= link_to "Добавить тексты из файлов", files_path %></li>
    <li><%= link_to "Добыть тексты из интернета", new_files_path %></li>
  </ul>
</small>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Название</th>
      <th>Текст</th>
      <th>Автор</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @local_texts.each do |local_text| %>
    <tr>
      <td><%= local_text.title %></td>
      <td><%= truncate(local_text.text, length: 520) %></td>
      <td><%= Author.find(local_text.author_id).name %></td>
      <td width="1%">
        <%= link_to raw('<i class="icon-align-justify icon-white"></i>'), local_text, class: 'btn btn-info btn-mini' %>
        <%= link_to raw('<i class="icon-edit icon-white"></i>'), edit_local_text_path(local_text),
            class: 'btn btn-warning btn-mini' %>
        <%= link_to raw('<i class="icon-trash icon-white"></i>'), local_text,
            method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-mini' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if @local_texts.count > 5 %>
  <ul class="nav nav-pills">
    <li><%= link_to 'Добавить текст', new_local_text_path %></li>
    <li><%= link_to "Добавить тексты из файлов", files_path %></li>
  </ul>
<% end %>

app/views/local_texts/new.html.erb
<legend>
	Добавить текст
</legend>
<%= render 'form' %>

app/views/local_texts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
    <h1><%= @local_text.title %></h1>
</div>
<div class="well">
<p>
  <%= @local_text.text %>
</p>
<div class="pull-right">Автор: <i><%= Author.find(@local_text.author_id).name %></i></div>
</div>

<div class="form-actions">
	<%= link_to 'Edit', edit_local_text_path(@local_text), class: 'btn btn-warning' %>
	<%= link_to 'Back', local_texts_path, class: 'btn' %>
</div>