config/routes.rb
Antiplug::Application.routes.draw do
  resources :check_texts

  resources :local_texts

  resources :authors

  resources :files
  match '/files/new', :to => 'files#new', :as => :new_files

  root :to => 'authors#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Antiplug</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<%= link_to "Antiplagiat", check_texts_path, class: 'brand' %>
				<div class="nav-collapse collapse">
					<ul class="nav">
			        <li><%= link_to "Авторы текстов", authors_path %></li>
			        <li><%= link_to "Тексты", local_texts_path %></li>
			        <li><%= link_to "Проверить текст", check_texts_path %></li>
			    </ul>
				</div>
			      <!--/.nav-collapse -->
		    </div>
	    </div>
    </div>
    <div class="clear"></div>
	<div class="container-fluid">
		<div class="row-fluid">
		    <div class="span12">
			    
			    	<%= yield %>
			    
		    </div>
		</div>
		<footer class="footer">
  <small>
    <%= link_to "This site", :root %>
    by Jeshio
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>
	</div>
</body>
</html>